#pragma once

#include "core/cpu/executable_memory.h"
#include "core/cpu/x86_decoder.h"

#include <cstdint>
#include <memory>
#include <span>
#include <string>
#include <vector>

namespace vshift::cpu {

class Arm64Jit final {
public:
    struct Result final {
        std::unique_ptr<Arm64Jit> jit;
        std::string error;

        bool ok() const noexcept { return error.empty() && jit != nullptr; }
    };

    static Result Compile(std::span<const X86Instruction> instructions);

    // Returns false on a host that is not ARM64. The generated bytes remain
    // inspectable through code(), which keeps decoder/JIT tests portable.
    bool Execute(std::uint32_t& result) const noexcept;

    std::span<const std::uint32_t> code() const noexcept { return code_; }

private:
    Arm64Jit(std::unique_ptr<ExecutableMemory> memory,
             std::vector<std::uint32_t> code) noexcept
        : memory_(std::move(memory)), code_(std::move(code)) {}

    std::unique_ptr<ExecutableMemory> memory_;
    std::vector<std::uint32_t> code_;
};

} // namespace vshift::cpu
